### ISSUE TITLE
the gui has messy code.

### ISSUE THREAD

**Issue by wileon994** [itsHenry35/ledu#39]
**Describe the bug**
The gui has messy code, seems like base64 encode.

**Screenshots**
![image](https://github.com/itsHenry35/ledu/assets/65838018/4fbf22d0-3435-4867-b0db-245c187753ba)

**Desktop (please complete the following information):**
 - OS: WSL(ubuntu 20.04)
 - How do you run the application: python main.py
 - Python Version 3.8.19

**Comment by itsHenry35** [comment]
Please use windows version before the fix. I'll try my best to fix this text encoding problem.

**Comment by itsHenry35** [comment]
https://blog.csdn.net/oZuoZuoZuoShi/article/details/118977701
